<?php
/**
 * Remove plugin-owned data when Simple Storage is deleted.
 *
 * Files in the storage are never deleted here. While some media exist only in the storage, the
 * rules in uploads/.htaccess stay so that old addresses keep working without the plugin; a proxy
 * rule is turned into a redirect, since proxy.php is deleted together with the plugin.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

global $wpdb;

$simple_storage_table  = $wpdb->prefix . 'simple_storage_files';
$simple_storage_remote = 0;
if ( $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $simple_storage_table ) ) === $simple_storage_table ) { // phpcs:ignore WordPress.DB.DirectDatabaseQuery
	$simple_storage_remote = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$simple_storage_table} WHERE remote = 1 AND local = 0" ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
}

$simple_storage_config_file = dirname( __DIR__, 2 ) . '/simple-storage-config.php';
$simple_storage_config      = is_file( $simple_storage_config_file ) ? include $simple_storage_config_file : null;
if ( ! is_array( $simple_storage_config ) || empty( $simple_storage_config['base'] ) || empty( $simple_storage_config['prefix'] ) ) {
	// No proxy configuration (it could not be written, or was removed): the stored settings and
	// the wp-config.php constants still say where the files live.
	$simple_storage_settings = get_option( 'simple_storage_settings', array() );
	$simple_storage_settings = is_array( $simple_storage_settings ) ? $simple_storage_settings : array();
	$simple_storage_base     = (string) ( $simple_storage_settings['public_url'] ?? '' );
	if ( '' === $simple_storage_base ) {
		$simple_storage_base = defined( 'SIMPLE_STORAGE_HOST' ) ? (string) SIMPLE_STORAGE_HOST : (string) ( $simple_storage_settings['host'] ?? '' );
	}
	if ( '' !== $simple_storage_base && ! preg_match( '#^https?://#i', $simple_storage_base ) ) {
		$simple_storage_base = 'https://' . $simple_storage_base;
	}
	$simple_storage_config = array(
		'base'   => $simple_storage_base,
		'prefix' => (string) ( $simple_storage_settings['prefix'] ?? '' ),
	);
}

$simple_storage_uploads  = wp_get_upload_dir();
$simple_storage_htaccess = trailingslashit( (string) $simple_storage_uploads['basedir'] ) . '.htaccess';
$simple_storage_block    = '/^# BEGIN Simple Storage\R.*?^# END Simple Storage\R?/ms';

if ( is_file( $simple_storage_htaccess ) && is_writable( $simple_storage_htaccess ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_is_writable
	$simple_storage_contents = (string) file_get_contents( $simple_storage_htaccess ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	$simple_storage_updated  = $simple_storage_contents;

	if ( 0 === $simple_storage_remote ) {
		$simple_storage_updated = (string) preg_replace( $simple_storage_block, '', $simple_storage_contents );
	} elseif ( is_array( $simple_storage_config ) && ! empty( $simple_storage_config['base'] ) && ! empty( $simple_storage_config['prefix'] ) ) {
		$simple_storage_target  = rtrim( (string) $simple_storage_config['base'], '/' ) . '/' . implode( '/', array_map( 'rawurlencode', explode( '/', (string) $simple_storage_config['prefix'] ) ) ) . '/';
		$simple_storage_rules   = "# BEGIN Simple Storage\n<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteRule ^([0-9]{4}/[0-9]{2}/.+)$ {$simple_storage_target}\$1 [R=302,L]\n</IfModule>\n# END Simple Storage\n";
		$simple_storage_updated = (string) preg_replace_callback( $simple_storage_block, static fn() => $simple_storage_rules, $simple_storage_contents );
	}

	if ( $simple_storage_updated !== $simple_storage_contents ) {
		if ( '' === trim( $simple_storage_updated ) ) {
			@unlink( $simple_storage_htaccess ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.unlink_unlink
		} else {
			file_put_contents( $simple_storage_htaccess, ltrim( $simple_storage_updated ), LOCK_EX ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		}
	}
}

if ( is_file( $simple_storage_config_file ) && str_contains( (string) file_get_contents( $simple_storage_config_file, false, null, 0, 256 ), 'Generated by Simple Storage' ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	@unlink( $simple_storage_config_file ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.WP.AlternativeFunctions.unlink_unlink
}

$wpdb->query( "DROP TABLE IF EXISTS {$simple_storage_table}" ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery, WordPress.DB.PreparedSQL.InterpolatedNotPrepared

foreach ( array( 'simple_storage_settings', 'simple_storage_state', 'simple_storage_job', 'simple_storage_lock', 'simple_storage_log', 'simple_storage_token', 'simple_storage_scan_seq', 'simple_storage_db_version', 'simple_storage_regenerating' ) as $simple_storage_option ) {
	delete_option( $simple_storage_option );
}

// Short-lived state: files held local, folder leases, Timber sizes that failed, the runner's flag.
$wpdb->query( "DELETE FROM {$wpdb->options} WHERE option_name LIKE '\\_transient\\_simple\\_storage\\_%' OR option_name LIKE '\\_transient\\_timeout\\_simple\\_storage\\_%'" ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery
delete_post_meta_by_key( '_simple_storage_client_processing' );

wp_unschedule_hook( 'simple_storage_offload_dir' );
wp_unschedule_hook( 'simple_storage_delete_remote' );
wp_unschedule_hook( 'simple_storage_timber_resize' );
wp_unschedule_hook( 'simple_storage_prune_dir' );

unset(
	$simple_storage_base,
	$simple_storage_block,
	$simple_storage_settings,
	$simple_storage_config,
	$simple_storage_config_file,
	$simple_storage_contents,
	$simple_storage_htaccess,
	$simple_storage_option,
	$simple_storage_remote,
	$simple_storage_rules,
	$simple_storage_table,
	$simple_storage_target,
	$simple_storage_updated,
	$simple_storage_uploads
);
