#!/usr/bin/env bash
# HTTP test of proxy.php: a fake site (tests/fake-site/router.php emulates the uploads/.htaccess
# rule) in front of the fake storage. Run from the plugin folder:
#
#   FAKE_STORAGE_ROOT=/tmp/fake FAKE_STORAGE_URL=http://127.0.0.1:8899 tests/proxy-http.sh
#
# PHP (default: php) must have cURL. The test writes the proxy configuration next to the plugins
# folder and removes it afterwards; it refuses to run if one already exists.

set -u
PHP="${PHP:-php}"
STORAGE_ROOT="${FAKE_STORAGE_ROOT:?FAKE_STORAGE_ROOT is required}"
STORAGE_URL="${FAKE_STORAGE_URL:-http://127.0.0.1:8899}"
PLUGIN="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$(cd "$PLUGIN/../.." && pwd)/simple-storage-config.php"
SITE_PORT=8898
SITE="http://127.0.0.1:$SITE_PORT"
WORK="$(mktemp -d)"
PREFIX="proxy-test-$RANDOM"
FAILED=0
CHECKS=0

if [ -e "$CONFIG" ]; then
	echo "Refusing to run: $CONFIG already exists." >&2
	exit 1
fi

cleanup() {
	[ -n "${SERVER_PID:-}" ] && kill "$SERVER_PID" 2>/dev/null
	rm -f "$CONFIG"
	rm -rf "$WORK" "$STORAGE_ROOT/$PREFIX"
}
trap cleanup EXIT

check() {
	CHECKS=$((CHECKS + 1))
	if [ "$1" = "$2" ]; then
		echo "  ok    $3"
	else
		FAILED=$((FAILED + 1))
		echo "  FAIL  $3 — expected [$2], got [$1]"
	fi
}

write_config() {
	cat > "$CONFIG" <<PHPCONFIG
<?php
// Generated by Simple Storage. Test configuration.
return array(
	'version' => 1,
	'mode' => '$1',
	'base' => '$STORAGE_URL',
	'prefix' => '$PREFIX',
	'uploads_path' => '/wp-content/uploads',
	'uploads_dir' => '$WORK/site/wp-content/uploads',
	'cache_control' => 'public, max-age=604800',
);
PHPCONFIG
}

mkdir -p "$WORK/site/wp-content/uploads/2024/05" "$STORAGE_ROOT/$PREFIX/2024/05"
head -c 1048576 /dev/urandom > "$STORAGE_ROOT/$PREFIX/2024/05/remote.bin"
printf 'png' > "$STORAGE_ROOT/$PREFIX/2024/05/Фото тест.png"
printf 'local' > "$WORK/site/wp-content/uploads/2024/05/local.jpg"
write_config proxy

"$PHP" -d opcache.enable=0 -d opcache.enable_cli=0 -S 127.0.0.1:$SITE_PORT -t "$WORK/site" "$PLUGIN/tests/fake-site/router.php" > "$WORK/site.log" 2>&1 &
SERVER_PID=$!
sleep 1

URL="$SITE/wp-content/uploads/2024/05/remote.bin"
EXPECTED_SHA="$(shasum -a 256 "$STORAGE_ROOT/$PREFIX/2024/05/remote.bin" | cut -d' ' -f1)"

curl -s -D "$WORK/h1" -o "$WORK/body" "$URL"
check "$(head -1 "$WORK/h1" | cut -d' ' -f2)" "200" "GET of a remote file answers 200 at its original address"
check "$(shasum -a 256 "$WORK/body" | cut -d' ' -f1)" "$EXPECTED_SHA" "streamed bytes are identical"
check "$(grep -i '^x-simple-storage:' "$WORK/h1" | tr -d '\r' | cut -d' ' -f2)" "proxy" "served by the proxy"
check "$(grep -i '^cache-control:' "$WORK/h1" | tr -d '\r' | cut -d' ' -f2-)" "public, max-age=604800" "Cache-Control from the configuration"
check "$(grep -ci '^location:' "$WORK/h1")" "0" "no redirect"

check "$(curl -s -I "$URL" | grep -i '^content-length:' | tr -d '\r' | cut -d' ' -f2)" "1048576" "HEAD reports the size"
check "$(curl -s -I "$URL" -o /dev/null -w '%{size_download}')" "0" "HEAD has no body"

curl -s -D "$WORK/h2" -o "$WORK/part" -H 'Range: bytes=100-199' "$URL"
check "$(head -1 "$WORK/h2" | cut -d' ' -f2)" "206" "Range answers 206"
check "$(wc -c < "$WORK/part" | tr -d ' ')" "100" "Range returns exactly the requested bytes"
check "$(grep -i '^content-range:' "$WORK/h2" | tr -d '\r' | cut -d' ' -f2-)" "bytes 100-199/1048576" "Content-Range passed through"
check "$(dd if="$STORAGE_ROOT/$PREFIX/2024/05/remote.bin" bs=1 skip=100 count=100 2>/dev/null | shasum -a 256 | cut -d' ' -f1)" "$(shasum -a 256 "$WORK/part" | cut -d' ' -f1)" "Range bytes are the right ones"

ETAG="$(grep -i '^etag:' "$WORK/h1" | tr -d '\r' | cut -d' ' -f2-)"
check "$(curl -s -o /dev/null -w '%{http_code}' -H "If-None-Match: $ETAG" "$URL")" "304" "If-None-Match answers 304"

check "$(curl -s -o /dev/null -w '%{http_code}' "$SITE/wp-content/uploads/2024/05/missing.jpg")" "404" "a file missing everywhere is 404"
curl -s -D "$WORK/h3" -o /dev/null "$SITE/wp-content/uploads/2024/05/%D0%A4%D0%BE%D1%82%D0%BE%20%D1%82%D0%B5%D1%81%D1%82.png"
check "$(head -1 "$WORK/h3" | cut -d' ' -f2)" "200" "unicode name with a space"
check "$(grep -i '^content-type:' "$WORK/h3" | tr -d '\r' | cut -d' ' -f2-)" "image/png" "Content-Type from the extension"
check "$(curl -s "$SITE/wp-content/uploads/2024/05/local.jpg")" "local" "a local file is served by the server itself"
check "$(curl -s -o /dev/null -w '%{http_code}' "$SITE/wp-content/uploads/2024/05/..%2F..%2F..%2Fwp-config.php")" "404" "path traversal refused"
check "$(curl -s -o /dev/null -w '%{http_code}' -X POST "$URL")" "405" "only GET and HEAD"
check "$(curl -s -o /dev/null -w '%{http_code}' "$SITE/wp-content/uploads/2024/05/.hidden")" "404" "hidden files refused"

write_config direct
check "$(curl -s -o /dev/null -w '%{http_code}' "$URL")" "302" "direct mode: the emulated rule redirects instead"
check "$(cd "$WORK" && "$PHP" -r '$_SERVER["REQUEST_URI"] = "/wp-content/uploads/2024/05/remote.bin"; require $argv[1];' "$PLUGIN/proxy.php")" "Not Found" "proxy.php itself serves nothing outside the proxy mode"
rm -f "$CONFIG"
check "$(curl -s -o /dev/null -w '%{http_code}' "$URL")" "404" "proxy does nothing without a configuration"

echo
if [ "$FAILED" -gt 0 ]; then
	echo "$FAILED of $CHECKS checks failed."
	exit 1
fi
echo "All $CHECKS checks passed."
