<?php
/**
 * Transparent proxy: streams a media file from the storage under its original uploads address.
 *
 * proxy.php loads this class without WordPress when uploads/.htaccess rewrites a request for a
 * missing file, and the plugin uses it as the fallback inside WordPress on servers without
 * .htaccess. It therefore relies on plain PHP only and reads its settings from a generated file
 * that contains no credentials: the storage address, the site folder and the uploads location.
 */

if ( ! defined( 'ABSPATH' ) && ! defined( 'SIMPLE_STORAGE_PROXY' ) ) {
	exit;
}

final class Simple_Storage_Proxy {
	public const CONFIG_VERSION = 1;
	public const CONFIG_MARKER = 'Generated by Simple Storage';

	private const TYPES = array(
		'jpg'  => 'image/jpeg',
		'jpeg' => 'image/jpeg',
		'jpe'  => 'image/jpeg',
		'png'  => 'image/png',
		'gif'  => 'image/gif',
		'webp' => 'image/webp',
		'avif' => 'image/avif',
		'heic' => 'image/heic',
		'svg'  => 'image/svg+xml',
		'ico'  => 'image/x-icon',
		'bmp'  => 'image/bmp',
		'tif'  => 'image/tiff',
		'tiff' => 'image/tiff',
		'mp4'  => 'video/mp4',
		'm4v'  => 'video/mp4',
		'mov'  => 'video/quicktime',
		'webm' => 'video/webm',
		'ogv'  => 'video/ogg',
		'ts'   => 'video/mp2t',
		'm3u8' => 'application/vnd.apple.mpegurl',
		'mp3'  => 'audio/mpeg',
		'm4a'  => 'audio/mp4',
		'ogg'  => 'audio/ogg',
		'oga'  => 'audio/ogg',
		'wav'  => 'audio/wav',
		'flac' => 'audio/flac',
		'pdf'  => 'application/pdf',
		'txt'  => 'text/plain; charset=utf-8',
		'vtt'  => 'text/vtt; charset=utf-8',
		'csv'  => 'text/csv; charset=utf-8',
		'json' => 'application/json',
		'zip'  => 'application/zip',
		'doc'  => 'application/msword',
		'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		'xls'  => 'application/vnd.ms-excel',
		'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
		'ppt'  => 'application/vnd.ms-powerpoint',
		'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		'woff' => 'font/woff',
		'woff2' => 'font/woff2',
	);

	/** Where the generated configuration lives: next to the plugins folder, as wp-content usually is. */
	public static function config_file(): string {
		return dirname( __DIR__, 3 ) . '/simple-storage-config.php';
	}

	/** @return array<string, mixed>|null */
	public static function load_config(): ?array {
		$file = self::config_file();
		if ( ! is_file( $file ) ) {
			return null;
		}

		$config = include $file;
		if ( ! is_array( $config ) || self::CONFIG_VERSION !== ( $config['version'] ?? null ) ) {
			return null;
		}
		foreach ( array( 'base', 'prefix', 'uploads_path', 'uploads_dir' ) as $key ) {
			if ( ! isset( $config[ $key ] ) || ! is_string( $config[ $key ] ) ) {
				return null;
			}
		}

		return $config;
	}

	/** Entry point of proxy.php. */
	public static function handle_request(): void {
		$config = self::load_config();
		if ( null === $config || 'proxy' !== ( $config['mode'] ?? '' ) ) {
			self::plain( 404, 'Not Found' );
		}

		$relative = self::relative_from_request( (string) ( $_SERVER['REQUEST_URI'] ?? '' ), (string) $config['uploads_path'] );
		if ( null === $relative ) {
			self::plain( 404, 'Not Found' );
		}

		self::serve( $config, $relative );
	}

	/** Uploads-relative media path of a request URI, or null. */
	public static function relative_from_request( string $uri, string $uploads_path ): ?string {
		$path = (string) parse_url( $uri, PHP_URL_PATH );
		$base = rtrim( $uploads_path, '/' ) . '/';
		if ( '' === $path || ! str_starts_with( $path, $base ) ) {
			return null;
		}

		$relative = rawurldecode( substr( $path, strlen( $base ) ) );

		return self::is_media_path( $relative ) ? $relative : null;
	}

	/** Same rule as Simple_Storage_Paths::is_media_path(), without WordPress. */
	public static function is_media_path( string $relative ): bool {
		if ( ! preg_match( '#^[0-9]{4}/[0-9]{2}/.+#', $relative ) || str_contains( $relative, "\0" ) || str_contains( $relative, '\\' ) || str_contains( $relative, '//' ) || str_ends_with( $relative, '/' ) ) {
			return false;
		}
		foreach ( explode( '/', $relative ) as $segment ) {
			if ( '' === $segment || '.' === $segment[0] ) {
				return false;
			}
		}

		return true;
	}

	/**
	 * Send the file: from disk when it is (again) local, otherwise streamed from the storage.
	 *
	 * @param array<string, mixed> $config
	 */
	public static function serve( array $config, string $relative ): void {
		$method = strtoupper( (string) ( $_SERVER['REQUEST_METHOD'] ?? 'GET' ) );
		if ( 'GET' !== $method && 'HEAD' !== $method ) {
			header( 'Allow: GET, HEAD' );
			self::plain( 405, 'Method Not Allowed' );
		}

		self::reset_output();

		$local = rtrim( (string) $config['uploads_dir'], '/' ) . '/' . $relative;
		if ( is_file( $local ) ) {
			self::send_local( $config, $local, 'HEAD' === $method );
		}

		$url = rtrim( (string) $config['base'], '/' ) . '/' . self::encode( (string) $config['prefix'] ) . '/' . self::encode( $relative );
		self::stream( $config, $url, $relative, 'HEAD' === $method );
	}

	/** @param array<string, mixed> $config */
	private static function stream( array $config, string $url, string $relative, bool $head ): void {
		if ( ! function_exists( 'curl_init' ) ) {
			self::plain( 502, 'Bad Gateway' );
		}

		$request = array();
		foreach ( array(
			'HTTP_RANGE'             => 'Range',
			'HTTP_IF_RANGE'          => 'If-Range',
			'HTTP_IF_NONE_MATCH'     => 'If-None-Match',
			'HTTP_IF_MODIFIED_SINCE' => 'If-Modified-Since',
		) as $key => $name ) {
			if ( isset( $_SERVER[ $key ] ) && '' !== $_SERVER[ $key ] ) {
				$request[] = $name . ': ' . str_replace( array( "\r", "\n" ), '', (string) $_SERVER[ $key ] );
			}
		}

		$status   = 0;
		$upstream = array();
		$started  = false;
		$rejected = false;

		$curl = curl_init( $url );
		curl_setopt_array(
			$curl,
			array(
				CURLOPT_HTTPHEADER      => $request,
				CURLOPT_NOBODY          => $head,
				CURLOPT_FOLLOWLOCATION  => true,
				CURLOPT_MAXREDIRS       => 2,
				CURLOPT_PROTOCOLS       => CURLPROTO_HTTP | CURLPROTO_HTTPS,
				CURLOPT_REDIR_PROTOCOLS => CURLPROTO_HTTP | CURLPROTO_HTTPS,
				CURLOPT_CONNECTTIMEOUT  => 10,
				CURLOPT_LOW_SPEED_LIMIT => 1,
				CURLOPT_LOW_SPEED_TIME  => 60,
				CURLOPT_USERAGENT       => 'SimpleStorage-Proxy',
				CURLOPT_HEADERFUNCTION  => static function ( $ch, string $line ) use ( &$status, &$upstream ): int {
					if ( preg_match( '#^HTTP/\S+\s+(\d{3})#', $line, $match ) ) {
						$status   = (int) $match[1];
						$upstream = array();
					} else {
						$parts = explode( ':', $line, 2 );
						if ( 2 === count( $parts ) ) {
							$upstream[ strtolower( trim( $parts[0] ) ) ] = trim( $parts[1] );
						}
					}

					return strlen( $line );
				},
				CURLOPT_WRITEFUNCTION   => static function ( $ch, string $chunk ) use ( &$started, &$rejected, &$status, &$upstream, $config, $relative ): int {
					if ( ! $started ) {
						if ( ! self::send_headers( $config, $relative, $status, $upstream ) ) {
							// An error page of the storage is not passed through; stop reading it.
							$rejected = true;

							return 0;
						}
						$started = true;
					}
					echo $chunk; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Binary file contents.
					flush();

					return connection_aborted() ? 0 : strlen( $chunk );
				},
			)
		);

		$result = curl_exec( $curl );

		if ( $started ) {
			// The body was streamed; a broken transfer can only be cut short at this point.
			exit;
		}
		if ( ! $rejected && false !== $result && 0 !== $status && self::send_headers( $config, $relative, $status, $upstream ) ) {
			// HEAD, 304 or an empty file: headers only.
			exit;
		}
		if ( in_array( $status, array( 403, 404, 410 ), true ) ) {
			self::plain( 404, 'Not Found' );
		}

		self::plain( 502, 'Bad Gateway' );
	}

	/**
	 * Headers for a storage response; false when the response must not be passed through.
	 *
	 * @param array<string, mixed>  $config
	 * @param array<string, string> $upstream
	 */
	private static function send_headers( array $config, string $relative, int $status, array $upstream ): bool {
		if ( ! in_array( $status, array( 200, 206, 304, 416 ), true ) ) {
			return false;
		}

		http_response_code( $status );
		header( 'Content-Type: ' . self::content_type( $relative, $upstream['content-type'] ?? '' ) );
		foreach ( array( 'content-length' => 'Content-Length', 'content-range' => 'Content-Range', 'etag' => 'ETag', 'last-modified' => 'Last-Modified' ) as $key => $name ) {
			if ( isset( $upstream[ $key ] ) ) {
				header( $name . ': ' . $upstream[ $key ] );
			}
		}
		header( 'Accept-Ranges: bytes' );
		self::common_headers( $config );

		return true;
	}

	/** @param array<string, mixed> $config */
	private static function send_local( array $config, string $file, bool $head ): void {
		$size  = (int) filesize( $file );
		$mtime = (int) filemtime( $file );
		$etag  = '"' . dechex( $mtime ) . '-' . dechex( $size ) . '"';

		header( 'Content-Type: ' . self::content_type( $file, '' ) );
		header( 'Last-Modified: ' . gmdate( 'D, d M Y H:i:s', $mtime ) . ' GMT' );
		header( 'ETag: ' . $etag );
		self::common_headers( $config );

		if ( trim( (string) ( $_SERVER['HTTP_IF_NONE_MATCH'] ?? '' ) ) === $etag ) {
			http_response_code( 304 );
			exit;
		}

		http_response_code( 200 );
		header( 'Content-Length: ' . $size );
		if ( ! $head ) {
			readfile( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_readfile
		}
		exit;
	}

	/** @param array<string, mixed> $config */
	private static function common_headers( array $config ): void {
		$cache = (string) ( $config['cache_control'] ?? '' );
		if ( '' !== $cache ) {
			header( 'Cache-Control: ' . $cache );
		}
		header( 'X-Content-Type-Options: nosniff' );
		header( 'X-Simple-Storage: proxy' );
	}

	private static function content_type( string $path, string $upstream ): string {
		$extension = strtolower( (string) pathinfo( $path, PATHINFO_EXTENSION ) );
		if ( isset( self::TYPES[ $extension ] ) ) {
			return self::TYPES[ $extension ];
		}

		return '' !== $upstream ? $upstream : 'application/octet-stream';
	}

	private static function encode( string $path ): string {
		return implode( '/', array_map( 'rawurlencode', explode( '/', $path ) ) );
	}

	/** Drop buffers and compression so that large files stream with constant memory. */
	private static function reset_output(): void {
		@ini_set( 'zlib.output_compression', 'Off' ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged, WordPress.PHP.IniSet.Risky
		while ( ob_get_level() > 0 ) {
			ob_end_clean();
		}
		if ( function_exists( 'set_time_limit' ) ) {
			@set_time_limit( 0 ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		}
		if ( function_exists( 'header_remove' ) && ! headers_sent() ) {
			header_remove( 'Set-Cookie' );
			header_remove( 'Cache-Control' );
			header_remove( 'Expires' );
			header_remove( 'Pragma' );
		}
	}

	private static function plain( int $status, string $message ): void {
		if ( ! headers_sent() ) {
			http_response_code( $status );
			header( 'Content-Type: text/plain; charset=utf-8' );
			header( 'Cache-Control: no-store' );
		}
		echo $message; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Fixed plain-text status line.
		exit;
	}

	/**
	 * PHP source of the configuration file.
	 *
	 * @param array<string, mixed> $config
	 */
	public static function config_source( array $config ): string {
		$config['version'] = self::CONFIG_VERSION;

		return "<?php\n// " . self::CONFIG_MARKER . ". Do not edit: the plugin rewrites this file.\n// It holds no credentials, only where the media are served from.\nreturn " . var_export( $config, true ) . ";\n"; // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export
	}
}
